version: "3.3"
services:
  app:
    container_name: fastapi-ml
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # set true only if INSTALL_DEV is unset in the environment.
        INSTALL_DEV: ${INSTALL_DEV-true}

    env_file:
      - .env

    ports:
      - 9000:9000      
